"""Generate the web UI's CSS custom-property token sheet from ``ui/theme.py``.

The tkinter GUI and the React web UI share ONE palette during the migration. This
script is the bridge: it reads the canonical color/spacing/radius definitions out
of ``ui/theme.py`` and emits ``webui/frontend/src/tokens.css`` as CSS custom
properties (``--zg-*``) — a ``:root`` block for light mode and a
``[data-theme="dark"]`` block for dark. A palette edit in ``theme.py`` + a re-run
keeps both apps in sync (drift is caught by ``tests/webui/test_tokens_gen.py``).

Why ast-parse instead of ``import ui.theme``? ``ui/theme.py`` imports ``tkinter``
(and ``ttkbootstrap``) at module scope, so importing it requires a Tk-capable
interpreter — false on a headless CI box or a minimal build image. The token data
we need (``_LIGHT``, ``_DARK``, ``_STATUS_BADGE``, ``SP``, ``RADIUS_BTN``,
``RADIUS_CHIP``) are all plain literals, so we parse them out of the AST with zero
imports and zero Tk dependency. The generator is therefore runnable anywhere.

Deterministic + idempotent: keys are emitted in the source dict order (stable
across runs), so re-running with an unchanged ``theme.py`` reproduces the file
byte-for-byte. Run: ``py -3.12 scripts/gen_web_tokens.py``.
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
_THEME_PY = _REPO / "ui" / "theme.py"
_OUT = _REPO / "webui" / "frontend" / "src" / "tokens.css"

_HEADER = "/* GENERATED by scripts/gen_web_tokens.py — do not hand-edit */\n"

# Score-band thresholds mirror ui.theme.score_band (>=70 good / >=45 mid / else
# low / negative or non-numeric none). The band -> palette-color mapping mirrors
# ui.theme.band_color: good=SUCCESS, mid=WARN, low=DANGER, none=FAINT. Emitted so
# the web score chips read identically to the tk score glyphs (Phase 1 score
# chips need the "none" band for unscored rows).
_SCORE_BANDS = {"good": "SUCCESS", "mid": "WARN", "low": "DANGER", "none": "FAINT"}


def _kebab(name: str) -> str:
    """theme.py palette key -> CSS token suffix. ``ACCENT_FG_DIM`` -> ``accent-fg-dim``."""
    return name.lower().replace("_", "-")


def _literal_eval_or_raise(name: str, value_node: ast.expr, key: str | None = None):
    """``ast.literal_eval(value_node)``, or a friendly ValueError naming the
    offending module-level assignment (+ dict key, if known) instead of a bare
    ValueError/SyntaxError — so a non-literal value in ui/theme.py points
    straight at the fix instead of an opaque ast traceback."""
    try:
        return ast.literal_eval(value_node)
    except (ValueError, SyntaxError) as exc:
        where = f"{name}[{key!r}]" if key is not None else name
        raise ValueError(
            f"{_THEME_PY.name} {where} is not a plain literal; "
            f"gen_web_tokens only supports literal values"
        ) from exc


def _literal(module: ast.Module, name: str):
    """Evaluate the module-level assignment ``name = <literal>`` via ast.literal_eval.
    Raises KeyError if the name isn't a top-level assignment at all, or ValueError
    (naming the assignment, and the specific dict key when the top-level value is
    a dict literal) if it's assigned but not a plain literal — e.g. a computed
    expression, a function call, or a name reference — since the generator has no
    interpreter to evaluate those (see module docstring: it must run without
    importing ui.theme's Tk dependency)."""
    for node in module.body:
        if isinstance(node, ast.Assign):
            for tgt in node.targets:
                if isinstance(tgt, ast.Name) and tgt.id == name:
                    if isinstance(node.value, ast.Dict):
                        # Walk key-by-key so a single computed value (e.g.
                        # theme.py _DARK['ACCENT'] = some_func()) names the exact
                        # offending key instead of failing the whole dict opaquely.
                        result = {}
                        for k_node, v_node in zip(node.value.keys, node.value.values):
                            key = (_literal_eval_or_raise(name, k_node)
                                   if k_node is not None else None)
                            result[key] = _literal_eval_or_raise(name, v_node, key)
                        return result
                    return _literal_eval_or_raise(name, node.value)
    raise KeyError(f"{name} not found as a top-level literal in {_THEME_PY.name}")


def _parse_theme(theme_src: str) -> dict:
    """Pull the token literals out of ui/theme.py source (no import, no Tk)."""
    mod = ast.parse(theme_src)
    return {
        "light": _literal(mod, "_LIGHT"),
        "dark": _literal(mod, "_DARK"),
        "status_badge": _literal(mod, "_STATUS_BADGE"),
        "sp": _literal(mod, "SP"),
        "radius_btn": _literal(mod, "RADIUS_BTN"),
        "radius_chip": _literal(mod, "RADIUS_CHIP"),
    }


def _palette_lines(palette: dict) -> list[str]:
    """`--zg-<key>: <hex>;` for every color in a palette, in source order."""
    return [f"  --zg-{_kebab(k)}: {v};" for k, v in palette.items()]


def _status_lines(badges: dict) -> list[str]:
    """`--zg-status-<status>: <hex>;` for one mode's STATUS_BADGE map."""
    return [f"  --zg-status-{_kebab(k)}: {v};" for k, v in badges.items()]


def _score_lines(palette: dict) -> list[str]:
    """`--zg-score-good|mid|low` aliased to this mode's band colors."""
    return [f"  --zg-score-{band}: {palette[src]};"
            for band, src in _SCORE_BANDS.items()]


def _shared_lines(data: dict) -> list[str]:
    """Mode-independent tokens: spacing scale + radii (emitted in :root only)."""
    lines = [f"  --zg-sp-{i}: {v}px;" for i, v in enumerate(data["sp"], start=1)]
    lines.append(f"  --zg-radius-btn: {data['radius_btn']}px;")
    lines.append(f"  --zg-radius-chip: {data['radius_chip']}px;")
    return lines


def render(theme_src: str) -> str:
    """The full tokens.css text for a given ui/theme.py source string."""
    data = _parse_theme(theme_src)

    root: list[str] = []
    root += _palette_lines(data["light"])
    root += _status_lines(data["status_badge"]["light"])
    root += _score_lines(data["light"])
    root += _shared_lines(data)

    dark: list[str] = []
    dark += _palette_lines(data["dark"])
    dark += _status_lines(data["status_badge"]["dark"])
    dark += _score_lines(data["dark"])

    out = [_HEADER.rstrip("\n"), ""]
    out.append(":root {")
    out += root
    out.append("}")
    out.append("")
    out.append('[data-theme="dark"] {')
    out += dark
    out.append("}")
    out.append("")  # trailing newline
    return "\n".join(out)


def generate(theme_py: Path = _THEME_PY) -> str:
    """Render tokens.css from the given theme.py path (default: repo ui/theme.py)."""
    return render(theme_py.read_text(encoding="utf-8"))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed tokens.css is out of date "
                         "(don't write)")
    args = ap.parse_args(argv)

    generated = generate()
    if args.check:
        current = _OUT.read_text(encoding="utf-8") if _OUT.exists() else ""
        if current != generated:
            print(f"tokens.css is STALE — re-run: py -3.12 {Path(__file__).name}",
                  file=sys.stderr)
            return 1
        print("tokens.css up to date")
        return 0

    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {_OUT.relative_to(_REPO)} ({len(generated)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
