"""REAP (Regional Education Applicant Program) per-state K-12 portals — free, no
key, public applicant sites. The single best ToS-safe channel for K-12 district
jobs (districts otherwise live on Frontline/AppliTrack — no clean feed — or
NEOGOV, which is ToS-blocked and must NEVER be scraped).

REAP is a family of per-STATE public teacher-job portals under the *reap.net
domain family, each a light PHP site generated by "Cybermill Communication".
Public job search is FREE to seekers with no login wall. Verified live
2026-07-02:

    search page:   https://www.{portal}/jobsrch.php?srch={cat}&position={pos}
    result rows:   <tr class="jobfirstrow"> with a /job_postings/{id}/{site}/{site}
                   detail link, a title (+ <div> subtitle + "Certificate:" line),
                   a school cell "District<br/>City,&nbsp;ST&nbsp;ZIP", and a date.

ROBOTS/ToS: every portal returns 404 for /robots.txt (no crawl restrictions
declared → allowed by default; checked live for usreap/moreap/ohreap/pareap on
2026-07-02). The site states it is "a FREE service to all applicants" and the
job search is a public, no-login page. We read it politely (a low rate limit, a
handful of category pages per covered state, cached once per cycle) and honor
the per-portal robots.txt at build time — if a portal's robots.txt ever appears
and disallows the search path, that portal is dropped (see _portal_allows).

STATE SCOPING: REAP only publishes portals for a handful of states (captured live
from usreap.net/otherStates.php on 2026-07-02: CT, MO, NM, OH, PA). A user in a
NON-covered state gets 0 results with NO noise (self-skip) — REAP simply doesn't
serve their state. Ohio (the teacher-columbus persona's state) IS covered.

INDUSTRY GATING: self-skips unless the active project's industry is an
education-family field (shared _EDUCATION_TOKENS, same gate as HigherEdJobs) AND
the user's location resolves to a covered state. An eng/nursing/trade project, or
an education seeker outside the 5 covered states, polls no REAP portal — so this
is safe to add to DAILY_SOURCES (inert for everyone it doesn't serve).
"""
from __future__ import annotations

import functools
import html as _html
import re
import tempfile
from pathlib import Path
from typing import Optional

import requests
from bs4 import BeautifulSoup

from models import JobResult
from search.higheredjobs_client import _EDUCATION_TOKENS
from search.http_util import cache_key
from search.single_feed_client import SingleFeedClient

REAP_SEARCH_URL = "https://www.{portal}/jobsrch.php"
REAP_JOB_URL = "https://www.{portal}{path}"
REAP_ROBOTS_URL = "https://www.{portal}/robots.txt"
REAP_RATE_LIMIT = 5

# TLS: the REAP portals present an INCOMPLETE chain (they omit the Sectigo R36
# intermediate that issued their leaf), so certifi alone raises
# CERTIFICATE_VERIFY_FAILED. We complete the chain by appending the bundled
# public intermediate to certifi — verification stays FULLY ON (chains to a
# trusted Sectigo root), never verify=False. See the .pem's header for details.
_REAP_INTERMEDIATE = "reap_sectigo_r36_intermediate.pem"


@functools.lru_cache(maxsize=1)
def _reap_ca_bundle() -> str:
    """Path to a combined CA bundle = certifi roots + the bundled REAP Sectigo
    intermediate, written once to a temp file. Falls back to certifi's default
    bundle if the intermediate asset is missing (REAP then fails closed on the
    TLS error rather than skipping verification)."""
    import certifi
    base = certifi.where()
    try:
        from coverage._paths import static_path
        inter = static_path(_REAP_INTERMEDIATE)
        inter_text = Path(inter).read_text(encoding="utf-8")
    except Exception:
        return base
    try:
        combined = Path(tempfile.gettempdir()) / "reap_ca_bundle.pem"
        combined.write_text(
            Path(base).read_text(encoding="utf-8") + "\n" + inter_text,
            encoding="utf-8")
        return str(combined)
    except OSError:
        return base

# US state (2-letter, lowercase) -> REAP portal host. Captured live from
# usreap.net/otherStates.php on 2026-07-02. Add a state = add a portal here as
# REAP expands. usreap.net (the national portal) is deliberately NOT a per-state
# route: it is its own applicant pool, not a superset of the state feeds.
STATE_PORTALS: dict[str, str] = {
    "ct": "ctreap.net",
    "mo": "moreap.net",
    "nm": "nmreap.net",
    "oh": "ohreap.net",
    "pa": "pareap.net",
}

# jobsrch.php ``srch`` category codes (captured live 2026-07-02). We poll the
# three education-relevant top-level categories; Support Services (400 —
# custodial/food/transport) is excluded as off-target for a teacher/educator.
#   100 Teaching Position, 200 Instructional Support, 300 School Administrative
SRCH_CATEGORIES: dict[int, str] = {
    100: "Teaching Position",
    200: "Instructional Support Position",
    300: "School Administrative Position",
}

# City, ST [ZIP] out of the school cell text "District  City, ST 43055".
_CITY_STATE_RE = re.compile(r"([A-Za-z .'\-]+),\s*([A-Z]{2})\b")


def _state_of(location: Optional[str]) -> Optional[str]:
    """The 2-letter lowercase US state a search location names, or None. Reuses
    the search_engine abbrev table (full name OR 2-letter token). "Columbus, OH"
    -> "oh"; "Cincinnati, Ohio" -> "oh"; a bare city / remote / "" -> None."""
    loc = (location or "").strip().lower()
    if not loc:
        return None
    from search.search_engine import _STATE_ABBREVS
    toks = [t.strip().rstrip(",.") for t in loc.replace(",", " ").split()]
    # 2-letter abbrev token wins (most explicit).
    for ab in set(_STATE_ABBREVS.values()):
        if ab in toks:
            return ab
    # else full state name substring.
    for full, ab in _STATE_ABBREVS.items():
        if full in loc:
            return ab
    return None


def _is_education(industry: Optional[str]) -> bool:
    """True when the industry is an education-family field (shared gate with
    HigherEdJobs). Empty/eng default -> False (inert)."""
    import industry_profile
    toks = set(industry_profile._tokens(industry or ""))
    return bool(toks & _EDUCATION_TOKENS)


def portal_for_location(location: Optional[str]) -> Optional[str]:
    """The REAP portal host serving a search location, or None if the state is not
    covered (or unresolvable). Pure/agnostic — no network."""
    st = _state_of(location)
    return STATE_PORTALS.get(st) if st else None


def _clean(text: str) -> str:
    """Collapse whitespace and NBSPs, unescape entities."""
    return _html.unescape(re.sub(r"\s+", " ", (text or "").replace("\xa0", " "))).strip()


def _clean_school(td) -> str:
    """Extract the school cell as "District\nCity, ST ZIP" — get_text with a
    newline separator keeps the <br/> boundary between the district name and the
    City,ST line (a space separator fuses them into one unsplittable blob)."""
    raw = td.get_text("\n", strip=True)
    lines = [
        _html.unescape(re.sub(r"[ \t]+", " ", ln.replace("\xa0", " "))).strip()
        for ln in raw.splitlines()
    ]
    return "\n".join(ln for ln in lines if ln)


def _parse_rows(html_text: str, portal: str) -> list[dict]:
    """Parse REAP result rows out of a jobsrch.php page into plain dicts
    (JSON-cacheable). Each ``<tr class="jobfirstrow">`` is one posting. A
    malformed page yields [] rather than raising."""
    try:
        soup = BeautifulSoup(html_text or "", "html.parser")
    except Exception:
        return []
    out: list[dict] = []
    for tr in soup.find_all("tr", class_="jobfirstrow"):
        link = tr.find("a", href=re.compile(r"/job_postings/"))
        if not link:
            continue
        path = link.get("href", "") or ""
        cells = tr.find_all("td", recursive=False)
        # Layout: [num][title/certificate][school City,ST][date][add-button].
        title_td = link.find_parent("td")
        title = _clean(title_td.get_text(" ", strip=True)) if title_td else _clean(link.get_text(" ", strip=True))
        # The school cell carries "District  City, ST ZIP".
        school_td = None
        for td in cells:
            classes = td.get("class") or []
            if "school" in classes:
                school_td = td
                break
        # The school cell is "District<br/>City,&nbsp;ST&nbsp;ZIP". Preserve that
        # <br> boundary with a newline separator so district and location split
        # cleanly (a plain-space join fuses "…SD Newark, OH" into one blob).
        school_text = _clean_school(school_td) if school_td else ""
        date_td = None
        for td in cells:
            classes = td.get("class") or []
            if "dateTD" in classes:
                date_td = td
                break
        date_text = _clean(date_td.get_text(" ", strip=True)) if date_td else ""
        out.append({
            "title": title,
            "school_text": school_text,
            "date": date_text,
            "path": path,
        })
    return out


def _split_school_location(school_text: str) -> tuple[str, str]:
    """"Newark City SD\nNewark, OH 43055" -> ("Newark City SD", "Newark, OH").

    The school cell is district then a "City, ST ZIP" line separated by the
    cell's <br/> (preserved as a newline by _clean_school). The LAST line that
    carries a City,ST is the location; everything before it is the district. A
    cell with no City,ST yields (whole text, ""); a bare City,ST with no district
    yields ("Unknown", "City, ST")."""
    text = (school_text or "").strip()
    if not text:
        return "Unknown", ""
    lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
    # Find the last line containing a City, ST — that's the location line.
    loc_idx = None
    match = None
    for i, ln in enumerate(lines):
        m = _CITY_STATE_RE.search(ln)
        if m:
            loc_idx, match = i, m
    if match is None:
        # No City,ST anywhere → the whole thing is the district name.
        return _clean(" ".join(lines)), ""
    city, state = match.group(1).strip(), match.group(2).strip()
    location = f"{city}, {state}"
    district_parts = lines[:loc_idx]
    # Any district text on the SAME line, before the city (rare, single-line cell).
    lead = lines[loc_idx][:match.start()].strip()
    if lead:
        district_parts.append(lead)
    district = _clean(" ".join(district_parts)) or "Unknown"
    return district, location


class ReapClient(SingleFeedClient):
    cache_subdir = "reap"
    rate_limit = REAP_RATE_LIMIT
    user_agent = "JobSearchTool/1.0 (personal use)"

    def __init__(self, cache_dir=None, cache_enabled: bool = True,
                 industry: Optional[str] = None, location: Optional[str] = None):
        super().__init__(cache_dir=cache_dir, cache_enabled=cache_enabled)
        if industry is None:
            try:
                from search.source_taxonomy import active_industry
                industry = active_industry()
            except Exception:
                industry = ""
        self.industry = industry or ""
        self.location = location or ""
        # Complete the REAP portals' incomplete TLS chain (bundled intermediate +
        # certifi). Verification stays ON — this only ADDS a trusted intermediate.
        self.session.verify = _reap_ca_bundle()
        # Resolve the portal ONCE: education-family field AND a covered state, else
        # inert. robots.txt is checked lazily at fetch time (network), not here.
        self.portal = None
        if _is_education(self.industry):
            self.portal = portal_for_location(self.location)
        self.active = self.portal is not None

    def _portal_allows(self, portal: str) -> bool:
        """Honor the portal's robots.txt live. Every REAP portal currently returns
        404 (no restrictions → allowed). If a robots.txt appears and disallows the
        search path for our UA, return False (skip that portal). A network error
        fails CLOSED (returns False) — we never fetch a portal we couldn't first
        verify as allowed."""
        url = REAP_ROBOTS_URL.format(portal=portal)
        try:
            self.limiter.acquire()
            resp = self.session.get(url, timeout=15)
        except requests.RequestException:
            return False
        if resp.status_code == 404:
            return True  # no robots.txt = no declared restrictions
        if resp.status_code != 200:
            return False  # anything unexpected -> be conservative, skip
        return _robots_allows(resp.text, "/jobsrch.php")

    def _fetch_category(self, portal: str, srch: int) -> list[dict]:
        def fetch():
            self.limiter.acquire()
            resp = self.session.get(
                REAP_SEARCH_URL.format(portal=portal),
                params={"srch": srch, "position": ""},
                timeout=30,
            )
            resp.raise_for_status()
            return {"rows": _parse_rows(resp.text, portal)}

        key = cache_key("reap", portal, srch)
        return self._cached(key, fetch).get("rows", [])

    def search(
        self,
        keyword: str,
        location: str = "",
        salary_min: Optional[int] = None,
        page: int = 1,
    ) -> dict:
        # Single page per category; page>1 has nothing more. Inert (non-education
        # or uncovered state) returns empty. robots.txt is honored before any
        # search fetch — a disallowing/unverifiable portal yields 0 rows, silently.
        if page > 1 or not self.active or not self.portal:
            return {"rows": []}
        if not self._portal_allows(self.portal):
            return {"rows": []}
        rows: list[dict] = []
        seen: set[str] = set()
        for srch in SRCH_CATEGORIES:
            for r in self._fetch_category(self.portal, srch):
                path = r.get("path", "")
                if path and path in seen:
                    continue
                if path:
                    seen.add(path)
                rows.append(r)
        return {"rows": rows, "_portal": self.portal, "_location": location or ""}

    def parse_results(self, raw: dict, source_keyword: str) -> list[JobResult]:
        from scrape.text_match import keyword_matches
        from search.remote_intent import (
            is_remote_only, metro_variant_set, remote_region_of,
            tag_nationwide_remote)
        portal = raw.get("_portal", "") or self.portal or ""
        search_loc = raw.get("_location", "") or ""
        remote = is_remote_only(search_loc)
        region = remote_region_of(search_loc) if remote else None
        metro_variants = None
        if search_loc and not remote:
            mv = metro_variant_set(search_loc)
            metro_variants = mv or None

        # Build every keyword-matching row first (with its localized JobResult),
        # tagging which rows fall inside the user's metro. REAP differs from the
        # national feeds (rnjobsite/higheredjobs) in one key way: the PORTAL is
        # already state-scoped, so EVERY row is in the user's state. So we
        # metro-localize with a STATE-level fail-open: prefer true-metro rows, but
        # if the metro filter would drop the whole (already in-state) result set,
        # keep the state rows rather than return 0. A Columbus teacher thus sees
        # Columbus-metro K-12 jobs when REAP has them, else the other in-state
        # postings (real, commutable locality) — never an empty feed for a covered
        # state. The remote-only path still tags rows nationwide via remote_intent.
        metro_rows: list[JobResult] = []
        all_rows: list[JobResult] = []
        for item in raw.get("rows", []) or []:
            title = (item.get("title", "") or "").strip()
            if not title:
                continue
            # Title carries the position + subtitle + certificate text — enough to
            # match a K-12 keyword; there is no body in the list view.
            if not keyword_matches(source_keyword, title):
                continue
            company, location = _split_school_location(item.get("school_text", ""))
            in_metro = True
            if remote:
                location = tag_nationwide_remote(location, region)
            elif metro_variants is not None:
                low = (location or "").lower()
                is_remote_row = "remote" in low
                in_metro = (not location) or is_remote_row or any(
                    v in low for v in metro_variants)
            path = item.get("path", "") or ""
            url = REAP_JOB_URL.format(portal=portal, path=path) if path and portal else ""
            job = JobResult(
                title=title,
                company=company,
                location=location,
                salary_min=None,
                salary_max=None,
                description="",
                url=url,
                source_keyword=source_keyword,
                created=item.get("date", "") or "",
                job_id=f"reap_{url}" if url else "",
                source_api="reap",
            )
            all_rows.append(job)
            if in_metro:
                metro_rows.append(job)
        # Metro-first, state-fallback (see comment above). No metro filter active
        # (remote / unresolvable / no location) => all_rows == metro_rows.
        return metro_rows if metro_rows else all_rows


def _robots_allows(robots_text: str, path: str) -> bool:
    """Minimal robots.txt check for the default (``*``) user-agent: True unless a
    ``Disallow`` rule under ``User-agent: *`` matches ``path``. Deliberately
    conservative and self-contained (no external robotparser dependency)."""
    ua_all = False
    disallows: list[str] = []
    for raw_line in (robots_text or "").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line or ":" not in line:
            continue
        field, _, value = line.partition(":")
        field = field.strip().lower()
        value = value.strip()
        if field == "user-agent":
            ua_all = (value == "*")
        elif field == "disallow" and ua_all:
            if value:
                disallows.append(value)
    return not any(path.startswith(d) for d in disallows)
