"""Drift guard: the committed webui/frontend/src/tokens.css must match what
``scripts/gen_web_tokens.py`` produces from the current ``ui/theme.py``.

If a palette color (or spacing/radius) changes in ``ui/theme.py`` without a
``py -3.12 scripts/gen_web_tokens.py`` re-run, the tk app and the web app fall out
of sync silently. This test fails loudly instead, telling the dev to regenerate.

Also pins the pieces of the contract the Phase-1+ frontend relies on: every
``_LIGHT`` key present as a kebab-cased ``--zg-*`` var, a ``[data-theme="dark"]``
block, status-badge + score-band + spacing + radius tokens.
"""
import importlib.util
import sys
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parent.parent.parent
_GEN_PY = _REPO / "scripts" / "gen_web_tokens.py"
_TOKENS_CSS = _REPO / "webui" / "frontend" / "src" / "tokens.css"


def _load_gen():
    """Import scripts/gen_web_tokens.py as a module (it isn't on the package path)."""
    spec = importlib.util.spec_from_file_location("_gen_web_tokens", _GEN_PY)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


gen = _load_gen()


def test_committed_tokens_match_generator():
    """The generator output equals the committed file, byte-for-byte."""
    expected = gen.generate()
    actual = _TOKENS_CSS.read_text(encoding="utf-8")
    assert actual == expected, (
        "tokens.css is out of date with ui/theme.py — "
        "re-run: py -3.12 scripts/gen_web_tokens.py"
    )


def test_check_mode_passes_on_committed_file():
    """``--check`` exits 0 when the file is current (mirrors the drift assert via
    the CLI path)."""
    assert gen.main(["--check"]) == 0


def test_header_comment_present():
    css = _TOKENS_CSS.read_text(encoding="utf-8")
    assert css.startswith(
        "/* GENERATED by scripts/gen_web_tokens.py — do not hand-edit */"
    )


def test_every_light_key_emitted_kebab_cased():
    """Every _LIGHT palette key appears as a kebab-cased --zg-* var in :root."""
    data = gen._parse_theme((_REPO / "ui" / "theme.py").read_text(encoding="utf-8"))
    css = _TOKENS_CSS.read_text(encoding="utf-8")
    for key in data["light"]:
        assert f"--zg-{gen._kebab(key)}:" in css, f"missing token for {key}"


def test_dark_block_present_and_overrides_window():
    css = _TOKENS_CSS.read_text(encoding="utf-8")
    assert '[data-theme="dark"] {' in css
    # dark WINDOW differs from light WINDOW -> the dark block genuinely overrides
    assert "--zg-window: #13171d;" in css
    assert "--zg-window: #f4f3ee;" in css


def test_status_badge_tokens_all_nine_statuses():
    data = gen._parse_theme((_REPO / "ui" / "theme.py").read_text(encoding="utf-8"))
    css = _TOKENS_CSS.read_text(encoding="utf-8")
    for status in data["status_badge"]["light"]:
        assert f"--zg-status-{gen._kebab(status)}:" in css


def test_score_band_tokens_present():
    css = _TOKENS_CSS.read_text(encoding="utf-8")
    for band in ("good", "mid", "low", "none"):
        assert f"--zg-score-{band}:" in css


def test_spacing_and_radius_tokens():
    css = _TOKENS_CSS.read_text(encoding="utf-8")
    # SP = (4, 8, 12, 16, 24, 32) -> --zg-sp-1..6
    for i, px in enumerate((4, 8, 12, 16, 24, 32), start=1):
        assert f"--zg-sp-{i}: {px}px;" in css
    assert "--zg-radius-btn: 7px;" in css
    assert "--zg-radius-chip: 6px;" in css


def test_output_is_deterministic():
    """Two renders of the same source are identical (idempotent generator)."""
    src = (_REPO / "ui" / "theme.py").read_text(encoding="utf-8")
    assert gen.render(src) == gen.render(src)


def test_non_literal_value_raises_friendly_error():
    """A computed (non-literal) value in a theme.py palette dict must raise a
    ValueError naming the assignment + the offending key, not an opaque
    ast.literal_eval ValueError/SyntaxError. Synthetic module: _DARK['ACCENT'] is
    a function call instead of a plain literal."""
    synthetic_src = (
        "def _compute():\n"
        "    return '#000000'\n"
        "\n"
        "_LIGHT = {'WINDOW': '#ffffff'}\n"
        "_DARK = {'WINDOW': '#000000', 'ACCENT': _compute()}\n"
        "_STATUS_BADGE = {'light': {}, 'dark': {}}\n"
        "SP = (4, 8)\n"
        "RADIUS_BTN = 7\n"
        "RADIUS_CHIP = 6\n"
    )
    with pytest.raises(ValueError, match=r"_DARK\['ACCENT'\].*not a plain literal"):
        gen._parse_theme(synthetic_src)
